const fs = require('fs');
const path = require('path');

const cardsDir = path.join(__dirname, '..', 'data', 'cards', 'en');
const outputPath = path.join(__dirname, '..', 'functions', 'enums.js');

const supertypes = new Set();
const subtypes = new Set();
const types = new Set();
const rarities = new Set();

const files = fs.readdirSync(cardsDir).filter((f) => f.endsWith('.json'));

for (const file of files) {
  const cards = JSON.parse(fs.readFileSync(path.join(cardsDir, file), 'utf8'));
  for (const card of cards) {
    if (card.supertype) supertypes.add(card.supertype);
    for (const s of card.subtypes || []) {
      if (s) subtypes.add(s);
    }
    for (const t of card.types || []) {
      if (t) types.add(t);
    }
    if (card.rarity) rarities.add(card.rarity);
  }
}

const output = `// Auto-generated by scripts/build-enums.js — do not edit manually
module.exports = {
  supertypes: ${JSON.stringify([...supertypes].sort())},
  subtypes: ${JSON.stringify([...subtypes].sort())},
  types: ${JSON.stringify([...types].sort())},
  rarities: ${JSON.stringify([...rarities].sort())},
};
`;

fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Enums written to ${outputPath}`);
console.log(`  supertypes: ${supertypes.size} unique values`);
console.log(`  subtypes: ${subtypes.size} unique values`);
console.log(`  types: ${types.size} unique values`);
console.log(`  rarities: ${rarities.size} unique values`);
